# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_help(object):
    def setupUi(self, Form_help):
        Form_help.setObjectName("Form_help")
        Form_help.resize(640, 480)
        Form_help.setStyleSheet("background:rgb(255, 170, 127)")
        self.gridLayoutWidget = QtWidgets.QWidget(Form_help)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, 419, 641, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_h_exit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_h_exit.setObjectName("pushButton_h_exit")
        self.gridLayout.addWidget(self.pushButton_h_exit, 0, 1, 1, 1)
        self.label_for_text = QtWidgets.QLabel(Form_help)
        self.label_for_text.setGeometry(QtCore.QRect(19, 30, 601, 371))
        self.label_for_text.setStyleSheet("background:rgb(255, 170, 127)")
        self.label_for_text.setText("")
        self.label_for_text.setObjectName("label_for_text")

        self.retranslateUi(Form_help)
        self.pushButton_h_exit.clicked.connect(Form_help.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form_help)

    def retranslateUi(self, Form_help):
        _translate = QtCore.QCoreApplication.translate
        Form_help.setWindowTitle(_translate("Form_help", "Form"))
        self.pushButton_h_exit.setText(_translate("Form_help", "&Exit"))
