# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_conf.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_conf(object):
    def setupUi(self, Form_conf):
        Form_conf.setObjectName("Form_conf")
        Form_conf.resize(640, 480)
        Form_conf.setStyleSheet("background:rgb(85, 255, 127)")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form_conf)
        self.buttonBox.setGeometry(QtCore.QRect(230, 420, 176, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Form_conf)
        QtCore.QMetaObject.connectSlotsByName(Form_conf)

    def retranslateUi(self, Form_conf):
        _translate = QtCore.QCoreApplication.translate
        Form_conf.setWindowTitle(_translate("Form_conf", "Form"))
